apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-optl-collector
  labels:
    app: my-optl-collector
spec:
  mode: deployment
  image: "otel/opentelemetry-collector:0.31.0"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:30080"

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: "my-jaeger-collector.observability.svc.cluster.local:14250"
        insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: try
    
    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, prometheus]

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-optl-collector
# spec:
#   ports:
#     - name: otlp # Default endpoint for otlp receiver.
#       port: 30080
#       protocol: TCP
#       targetPort: 30080
#       nodePort: 30080
#     - name: metrics # Default endpoint for metrics.
#       port: 8889
#       protocol: TCP
#       targetPort: 8889
#   selector:
#     app: my-optl-collector
#   type: NodePort